### ISSUE TITLE
Add in Stop functionality

### ISSUE THREAD

**Issue by reborn1002** [UniTradeApp/unitrade-contracts#9]
Right now we have ability for users to place limit orders and market orders. We need to add in ability for stop orders. 

With the limit order if a token price is at $1 and the user inputs a limit sell order at $0.90 the order will be executed immediately as the current price is higher than their sell order price. With a stop loss order if the current price is $1 and they input a stop loss sell order at $0.90 then the order would only be processed when the price actually reaches the target.

You can reach more about that here, https://www.investopedia.com/ask/answers/04/022704.asp

**Comment by marcelomorgado** [comment]
This implementation will require subgraph, executor-service, and frontend changes.
